name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    env:
      DOCKER_IMAGE_NAME: parthibansrinivasan/reactui:v5
      IMAGE_NAME: codelabs
      GIT_TAG: v5

    steps:
    - name: Checkout - clone repo
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build - NPM Install  
      #working-directory: /home/runner/work/codelabs/ 
      #git clone https://github.com/parthi-sysdig/codelabs
      # /home/runner/work/codelabs/codelabs/site/node_modules/node-sass
      run: | 
        cd site 
        pwd
        npm install 
        npm install -g gulp-cli 

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PW }}
          
    - name: Docker build and Push the image
      uses: docker/build-push-action@v3
      with:
         push: true 
         tags: ${{ env.DOCKER_IMAGE_NAME }}
         
    - name: Set-up google
      uses: google-github-actions/setup-gcloud@main
      with:
         service_account_key: ${{ secrets.SA_KEY_GCP }}  
         project_id: ${{ secrets.GCP_PROJECT_ID }}
         export_default_credentials: true
         
    - name: Build docker image 
      run: |-
        pwd
        docker build -t $IMAGE_NAME:latest .  
        docker build -t $DOCKER_IMAGE_NAME .  
        
    - name: Config docker client
      run: |-
        gcloud auth configure-docker --quiet
        
    - name: Push to GCR repo
      env: 
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |-
        gcloud docker tag $GCR_IMAGE_NAME:$GIT_TAG gcr.io/$PROJECT_ID/$GCR_IMAGE_NAME:$GIT_TAG
        gcloud docker push $GCR_IMAGE_NAME:$GIT_TAG gcr.io/$PROJECT_ID/$GCR_IMAGE_NAME:$GIT_TAG
    
    
         
